PROGPLAT_ARCH         =arm8
PROGPLAT_TYPE         =exps1
PROGPLAT_PARAMS       =cache_multiw
PROGPLAT_BOARD        =rpi3
PROGPLAT_RUN_TIMEOUT  =10
__PROGPLAT_MUL_RUNS__ =10
__PROGPLAT_MEM_DEF_TRAIN__  =expmem_byte_to_word(0x99)

