PROGPLAT_ARCH         =arm8
PROGPLAT_TYPE         =exps1
PROGPLAT_PARAMS       =cache_multiw
PROGPLAT_BOARD        =rpi4
PROGPLAT_RUN_TIMEOUT  =6
__PROGPLAT_MUL_RUNS__ =10
__PROGPLAT_MEM_DEF_1__  =expmem_byte_to_word(0x1)
__PROGPLAT_MEM_DEF_2__  =expmem_byte_to_word(0x2)
PROGPLAT_LOAD_ELF     =program.elf

