(* riscvLib - generated by L3 - Thu Dec 05 14:01:53 2024 *)
structure riscvLib :> riscvLib =
struct
open HolKernel boolLib bossLib
open utilsLib riscvTheory
val () = (numLib.prefer_num (); wordsLib.prefer_word ())
fun riscv_compset thms =
   utilsLib.theory_compset (thms, riscvTheory.inventory)
end